server:
  port: 8888

#connect to mysql
#yremp.live ????????????ip?? | example ???????????
#spring.datasource.url=jdbc:mysql://101.132.121.193:3306/zhanxin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true
#??????
#spring.datasource.username=zhanxin
#???????
#spring.datasource.password=GAkEC8iNwbyzAY35
#JDBC??????
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#mybatis.mapper-locations=classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.121.193:3306/zhanxin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: zhanxin
    password: GAkEC8iNwbyzAY35
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    port: 25
    #这是你的邮箱
    username: zhanxinwang2022@163.com
    #这是你QQ邮箱内第三方POP3/SMTP服务密码需要开启，在QQ邮箱-设置-账户
    password: AJZLISGYZSNSLNVY
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true


file:
  doc-dir: file/

path:
  video-upload-path: "C:/opt/ZhanXin/videos/"
  picture-upload-path: "C:/opt/ZhanXin/images/"